name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install

      - name: Print commit
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Check style
        run: npm run eslint

      - name: Build
        run: npm run build

      # On Pull Request as a failing build should not be pushed to main branch
      - name: Discord Webhook Notify Build Failure
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: failure()
        with:
          severity: error
          text: Build failed!
          description: Build failed with commit ${{ github.event.pull_request.head.repo.html_url}}/commit/${{ github.event.pull_request.head.sha}} by ${{ github.event.pull_request.head.user.login }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Test
        run: npm run test

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: E2E Tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Trigger deployment
        id: trigger-deployment
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        run: curl https://api.render.com/deploy/srv-${{secrets.RENDER_SERVICE_ID }}?key=${{secrets.RENDER_API_KEY }}

      - name: Discord Webhook Notify Deploy Success
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: steps.trigger-deployment.outcome == 'success'
        with:
          severity: info
          text: A new version was deployed!
          description: Deployed to https://full-stack-open-pokedex-ki28.onrender.com/ by ${{ github.event.commits[0].committer.username }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch